security:
    password_hashers:
        App\Entity\User: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|assets)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: _username
                password_parameter: _password
                enable_csrf: true
            logout:
                path: app_logout
                target: app_login
    access_control:
        - { path: ^/api/userdata, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/dashboard, roles: IS_AUTHENTICATED_FULLY }
