webpack_encore:
    # If/when you use Webpack Encore, you can enable this block and build to public/build
    # output_path: '%kernel.project_dir%/public/build'
    script_attributes:
        defer: true

# IMPORTANT: We're using AssetMapper. Do not set a json_manifest_path here,
# otherwise all asset() calls will require public/build/manifest.json.
